pipeline {
  stages {
    stage('Build Release') {
      post {
          always {
              archive "target/**/*"
              junit 'target/surefire-reports/*.xml'
          }
      }
    }
  }
}

